name: flutter_riverpod_template
description: 'Flutter Riverpod App Template: Showcases Riverpod for state management in Flutter.'
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.1'
  flutter: '>=3.16.1'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.3+1
  go_router: ^13.1.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  http_mock_adapter: ^0.6.1
  mocktail_image_network: ^1.1.0
  mocktail: ^1.0.3
  remove_from_coverage: ^2.0.0

flutter:
  uses-material-design: true
