name: Run tests

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install project dependencies
        run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Run static analysis
        run: flutter analyze .

      - name: Run tests
        run: |
          flutter test --no-pub --coverage --test-randomize-ordering-seed random
          flutter pub run remove_from_coverage -f coverage/lcov.info -r '\..*\.dart'

      - uses: codecov/codecov-action@v3
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
